@url = http://localhost:5035

###
GET {{url}}/reservations

###
GET {{url}}/reservations/cf7fb8f1-2caa-4886-976f-da0e1eb1dd13

###
POST {{url}}/reservations
Content-Type: application/json

{
    "parkingSpotId": "00000000-0000-0000-0000-000000000001",
    "date": "2024-02-02",
    "employeeName": "Joe Dou",
    "licencePlate": "XYZ123"
}

###
PUT {{url}}/reservations/1
Content-Type: application/json

{
    "id": 1,
    "da"
    "licencePlate": "XYZzz"
}

###
DELETE {{url}}/reservations/1